---

- name: catalogue
  hosts: catalogue
  become: yes
  tasks:
    - name: Disable nodejs and enable nodejs:18
      ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

    - name: Installing nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: present
        
    - name: Adding roboshop user
      ansible.builtin.user:
        name: roboshop

    - name: Creating a directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Downloading the zip file
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
        dest: /tmp/catalogue.zip

    - name: unzip the file
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /app
        remote_src: yes

    - name: install npm
      ansible.builtin.command: npm install
      args:
        chdir: /app

    - name: coping catalogue service
      ansible.builtin.copy:
        src: catalogue.service
        dest: /etc/systemd/system/catalogue.service

    - name: reload the daemon
      ansible.builtin.

