---

- name: mongodb
  hosts: mongodb
  become: yes
  tasks:
  - name: copy from mongodb.repo
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: Installin mongodb-org
    ansible.builtin.package:
      name : mongod-org
      state: present

  - name: start and enable mongod service
    ansible.builtin.service:
      name: mongod
      state: started
      enabled: yes

  - name: Change mongodb to global access
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: restarting the mongod
    ansible.builtin.service:
      name: mongod
      state: restarted